# Generated by Django 5.2.8 on 2026-02-24 13:10

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[utils.validators.MobileValidtor()],
                verbose_name="mobile",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[utils.validators.FullPersianLetterValidator()],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet",
            field=models.IntegerField(default=0, verbose_name="wallet"),
        ),
    ]
