# Generated by Django 5.2.8 on 2026-02-24 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminactionlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "admin action log",
                "verbose_name_plural": "admin action logs",
            },
        ),
        migrations.AlterModelOptions(
            name="chargewalletrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "charge wallet request",
                "verbose_name_plural": "charge wallet requests",
            },
        ),
        migrations.AlterModelOptions(
            name="wallethistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "wallet history",
                "verbose_name_plural": "wallet histories",
            },
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="admin",
            ),
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="string_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="string details"
            ),
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="structured_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="structured details"
            ),
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="amount",
            field=models.IntegerField(verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="backup",
            field=models.JSONField(blank=True, default=dict, verbose_name="backup"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="docs",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="admin/documents/",
                verbose_name="documents",
            ),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="is_successful",
            field=models.BooleanField(default=False, verbose_name="successful"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="response"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="chargewalletrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_charge_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="wallethistory",
            name="before",
            field=models.IntegerField(verbose_name="before charge"),
        ),
        migrations.AlterField(
            model_name="wallethistory",
            name="charge",
            field=models.IntegerField(verbose_name="charge amount"),
        ),
        migrations.AlterField(
            model_name="wallethistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="wallethistory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="wallethistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="wallethistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
